server:
  servlet:
    context-path: /myjpa

spring:
  datasource:
    url: jdbc:mysql://192.168.126.131:33306/myjpa?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
